#MySQL数据库
spring:
  datasource:
    name: blog  #数据库名
    url: jdbc:mysql://localhost:3306/blog #url
    username: root  #用户名
    password: root  #密码
    driver-class-name: com.mysql.cj.jdbc.Driver  #数据库链接驱动

#Redis数据库
